# Generated by Django 5.0.3 on 2024-05-17 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shelter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=20)),
                ('phone_number', models.PositiveIntegerField(default=123456789)),
            ],
        ),
    ]
