# Generated by Django 4.2.6 on 2024-05-28 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnimalApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelter',
            name='address',
            field=models.CharField(max_length=200),
        ),
    ]
